import type { Config } from 'tailwindcss'

export default {
    content: [
        './components/**/*.{js,vue,ts}',
        './layouts/**/*.vue',
        './pages/**/*.vue',
        './plugins/**/*.{js,ts}',
        './app.vue',
        './error.vue',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'surface-container-lowest': '#ffffff',
                'tertiary-fixed': '#ffdcc3',
                'primary': '#1d2b3e',
                'error': '#ba1a1a',
                'on-secondary-fixed': '#0f0069',
                'on-primary-fixed-variant': '#3a485c',
                'on-secondary-container': '#fffbff',
                'outline': '#75777d',
                'primary-container': '#334155',
                'on-tertiary': '#ffffff',
                'on-primary': '#ffffff',
                'on-surface': '#0b1c30',
                'on-error-container': '#93000a',
                'on-surface-variant': '#44474c',
                'on-error': '#ffffff',
                'inverse-surface': '#213145',
                'tertiary': '#442100',
                'surface-dim': '#cbdbf5',
                'tertiary-fixed-dim': '#ffb77d',
                'inverse-on-surface': '#eaf1ff',
                'on-tertiary-fixed': '#2f1500',
                'inverse-primary': '#b9c7e0',
                'secondary-container': '#645efb',
                'error-container': '#ffdad6',
                'on-secondary-fixed-variant': '#3323cc',
                'on-primary-fixed': '#0d1c2f',
                'on-tertiary-container': '#fc922b',
                'surface-container-low': '#eff4ff',
                'secondary': '#4b41e1',
                'primary-fixed': '#d5e3fd',
                'outline-variant': '#c5c6cd',
                'primary-fixed-dim': '#b9c7e0',
                'surface-container': '#e5eeff',
                'surface': '#f8f9ff',
                'surface-bright': '#f8f9ff',
                'on-secondary': '#ffffff',
                'surface-tint': '#515f74',
                'background': '#f8f9ff',
                'secondary-fixed': '#e2dfff',
                'surface-container-high': '#dce9ff',
                'on-primary-container': '#9eadc5',
                'on-background': '#0b1c30',
                'tertiary-container': '#653400',
                'secondary-fixed-dim': '#c3c0ff',
                'on-tertiary-fixed-variant': '#6e3900',
                'surface-container-highest': '#d3e4fe',
                'surface-variant': '#d3e4fe',
            },
            borderRadius: {
                DEFAULT: '1rem',
                lg: '2rem',
                xl: '3rem',
                full: '9999px',
            },
            spacing: {
                'space-lg': '2.5rem',
                'gutter-mobile': '1rem',
                'margin-mobile': '1.5rem',
                'space-xl': '4.5rem',
                'space-xs': '0.375rem',
                'space-sm': '0.75rem',
                'space-md': '1.25rem',
                'space-2xl': '8rem',
                'gutter': '2rem',
                'margin': '4rem',
            },
            fontFamily: {
                'headline-sm': ['Newsreader'],
                'body-xl': ['Plus Jakarta Sans'],
                'body-sm': ['Plus Jakarta Sans'],
                'headline-md': ['Newsreader'],
                'body-lg': ['Plus Jakarta Sans'],
                'label-sm': ['Plus Jakarta Sans'],
                'display-lg-mobile': ['Newsreader'],
                'body-md': ['Plus Jakarta Sans'],
                'display-md-mobile': ['Newsreader'],
                'display-lg': ['Newsreader'],
                'headline-lg': ['Newsreader'],
                'label-md': ['Plus Jakarta Sans'],
                'display-md': ['Newsreader'],
            },
            fontSize: {
                'headline-sm': ['1.5rem', { lineHeight: '2rem', fontWeight: '500' }],
                'body-xl': ['1.25rem', { lineHeight: '2rem', fontWeight: '400' }],
                'body-sm': ['0.875rem', { lineHeight: '1.375rem', fontWeight: '400' }],
                'headline-md': ['2rem', { lineHeight: '2.5rem', letterSpacing: '-0.005em', fontWeight: '400' }],
                'body-lg': ['1.125rem', { lineHeight: '1.75rem', fontWeight: '400' }],
                'label-sm': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.04em', fontWeight: '600' }],
                'display-lg-mobile': ['2.75rem', { lineHeight: '3.25rem', letterSpacing: '-0.015em', fontWeight: '400' }],
                'body-md': ['1rem', { lineHeight: '1.625rem', fontWeight: '400' }],
                'display-md-mobile': ['2.25rem', { lineHeight: '2.75rem', letterSpacing: '-0.01em', fontWeight: '400' }],
                'display-lg': ['4.5rem', { lineHeight: '5rem', letterSpacing: '-0.02em', fontWeight: '400' }],
                'headline-lg': ['2.5rem', { lineHeight: '3rem', letterSpacing: '-0.01em', fontWeight: '400' }],
                'label-md': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.01em', fontWeight: '600' }],
                'display-md': ['3.5rem', { lineHeight: '4rem', letterSpacing: '-0.02em', fontWeight: '400' }],
            },
        },
    },
    plugins: [],
} satisfies Config