// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026-05-21, 9:01:17 p.m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/Documents/Jayden/Jayden-Portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Documents/Jayden/Jayden-Portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Documents/Jayden/Jayden-Portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Documents/Jayden/Jayden-Portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Documents/Jayden/Jayden-Portfolio/plugins/**/*.{js,ts,mjs}","D:/Documents/Jayden/Jayden-Portfolio/composables/**/*.{js,ts,mjs}","D:/Documents/Jayden/Jayden-Portfolio/utils/**/*.{js,ts,mjs}","D:/Documents/Jayden/Jayden-Portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Documents/Jayden/Jayden-Portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Documents/Jayden/Jayden-Portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Documents/Jayden/Jayden-Portfolio/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;